@host = http://hapi.fhir.org/baseR4

// ============================== Cooks and household ============================== //

### Household
PUT {{host}}/Organization/HouseholdCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/Organization-HouseholdCook.json


### Cook: Milja Cook
PUT {{host}}/Practitioner/MiljaCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/Practitioner-MiljaCook.json

### Cook: Ron Cook
PUT {{host}}/Practitioner/RonCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/Practitioner-RonCook.json


### Cook in Household: Milja Cook @ Household Cook
PUT {{host}}/PractitionerRole/MiljaCookHouseholdCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PractitionerRole-MiljaCookHouseholdCook.json

### Cook in Household: Ron Cook @ Household Cook
PUT {{host}}/PractitionerRole/RonCookHouseholdCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PractitionerRole-RonCookHouseholdCook.json

// ------------------------------------------------------------------------------------ //

### All cooks (Practitioner) of the "logged in" household (Organization)
GET {{host}}/Practitioner?_has:PractitionerRole:practitioner:organization.name=Household Cook HTTP/1.1
Content-Type: application/fhir+json
