@host = http://hapi.fhir.org/baseR4


// ============================== Recipes ============================== //

### 1. Asparagus tart with bresaola
PUT {{host}}/PlanDefinition/a05feeec-019a-4e29-ad2b-b7c3b3940f49 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-a05feeec-019a-4e29-ad2b-b7c3b3940f49.json


### 2. Spinach lasagne
PUT {{host}}/PlanDefinition/2bd95802-2006-484f-b01d-ab86b53608bd HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-2bd95802-2006-484f-b01d-ab86b53608bd.json


### 3. Goulash soup
PUT {{host}}/PlanDefinition/18fd2817-aafa-4234-9fa8-cc7e5fe7c859 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-18fd2817-aafa-4234-9fa8-cc7e5fe7c859.json


### 4. Pear tart with hazelnuts
PUT {{host}}/PlanDefinition/e46400ab-889f-45ca-93ef-f7a34cafb984 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-e46400ab-889f-45ca-93ef-f7a34cafb984.json


### 5. Lemon-pumpkin fish stew
PUT {{host}}/PlanDefinition/65257078-33e4-48b2-90ce-7f8a086f49b9 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-65257078-33e4-48b2-90ce-7f8a086f49b9.json


### 6. Beetroot pralines with macadamia
PUT {{host}}/PlanDefinition/56d58ce7-dfb2-4d3c-adbf-b85d69368815 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-56d58ce7-dfb2-4d3c-adbf-b85d69368815.json


### 7. Tomato sugo
PUT {{host}}/PlanDefinition/040537d6-0fbf-4db9-ac4f-14b874b650f6 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-040537d6-0fbf-4db9-ac4f-14b874b650f6.json


### 8. Strawberry bowle
PUT {{host}}/PlanDefinition/9a8a285c-f79d-4d52-8d3d-01fe7b53e8d3 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-9a8a285c-f79d-4d52-8d3d-01fe7b53e8d3.json


### All recipes (PlanDefinition) of the "logged in" household -> for list of recipes
GET {{host}}/PlanDefinition?publisher=Household Cook&status=active HTTP/1.1
Content-Type: application/fhir+json


### Spargeltarte
GET {{host}}/PlanDefinition/a05feeec-019a-4e29-ad2b-b7c3b3940f49
Content-Type: application/fhir+json


// ============================== Cooks and household ============================== //

### Household
PUT {{host}}/Organization/HouseholdCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/Organization-HouseholdCook.json


### Cook: Milja Cook
PUT {{host}}/Practitioner/MiljaCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/Practitioner-MiljaCook.json

### Cook: Ron Cook
PUT {{host}}/Practitioner/RonCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/Practitioner-RonCook.json


### Cook in Household: Milja Cook @ Household Cook
PUT {{host}}/PractitionerRole/MiljaCookHouseholdCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PractitionerRole-MiljaCookHouseholdCook.json

### Cook in Household: Ron Cook @ Household Cook
PUT {{host}}/PractitionerRole/RonCookHouseholdCook HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PractitionerRole-RonCookHouseholdCook.json


### All cooks (Practitioner) of the "logged in" household (Organization)
GET {{host}}/Practitioner?_has:PractitionerRole:practitioner:organization.name=Household Cook HTTP/1.1
Content-Type: application/fhir+json
