@host = http://hapi.fhir.org/baseR4




### Asparagus tart with bresaola
PUT {{host}}/PlanDefinition/a05feeec-019a-4e29-ad2b-b7c3b3940f49 HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-a05feeec-019a-4e29-ad2b-b7c3b3940f49.json


### Spinach lasagne
PUT {{host}}/PlanDefinition/2bd95802-2006-484f-b01d-ab86b53608bd HTTP/1.1
Content-Type: application/fhir+json

< fsh-generated/resources/PlanDefinition-2bd95802-2006-484f-b01d-ab86b53608bd.json




### All recipes (PlanDefinition) of the "logged in" household -> for list of recipes
GET {{host}}/PlanDefinition?publisher=Household Cook&status=active HTTP/1.1
Content-Type: application/fhir+json


### Spargeltarte
GET {{host}}/PlanDefinition/a05feeec-019a-4e29-ad2b-b7c3b3940f49
Content-Type: application/fhir+json

